name: Master Workflow
on:
  push:
    branches:
    - master
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Node Setup
        uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - name: NPM Install
        run: npm install
      - name: NPM Build
        run: npm run build
      - name: NPM Test
        run: npm run test
